// <auto-generated />
using CW2_Assignment_App.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CW2_Assignment_App.Migrations
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20231221055214_6Db")]
    partial class _6Db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CW2_Assignment_App.Model.Badges", b =>
                {
                    b.Property<string>("BadgesID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("badgeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateGained")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profileID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BadgesID");

                    b.ToTable("Badges", "CW2");
                });

            modelBuilder.Entity("CW2_Assignment_App.Model.Comments", b =>
                {
                    b.Property<string>("CommentsID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentsID");

                    b.ToTable("Comments", "CW2");
                });

            modelBuilder.Entity("CW2_Assignment_App.Model.Leaderboard", b =>
                {
                    b.Property<string>("LeaderboardID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FriendsRanking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GlobalRanking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeaderboardID");

                    b.ToTable("Leaderboard", "CW2");
                });

            modelBuilder.Entity("CW2_Assignment_App.Model.Profile", b =>
                {
                    b.Property<string>("profileID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("archivedStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registerDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("profileID");

                    b.ToTable("Profile", "CW2");
                });

            modelBuilder.Entity("CW2_Assignment_App.Model.Trail", b =>
                {
                    b.Property<string>("TrailID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrailID");

                    b.ToTable("Trail", "CW2");
                });

            modelBuilder.Entity("CW2_Assignment_App.Model.User", b =>
                {
                    b.Property<string>("userID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userID");

                    b.ToTable("Users", "CW2");
                });
#pragma warning restore 612, 618
        }
    }
}
